// frontend/src/views/Home.tsx
import { DeleteOutlined } from '@ant-design/icons'
import { Button, Card, Checkbox, Col, DatePicker, Form, Input, message, Progress, Row, Select, Space, Tag } from 'antd'
import type { Dayjs } from 'dayjs'
import { useEffect, useMemo, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { clearTripMemory, generateTripPlan } from '@/services/api'
import type { TripFormData } from '@/types'

const PROFILE_STORAGE_KEY = 'trip_profile_id'
const CONVERSATION_STORAGE_KEY = 'trip_conversation_id'

const preferenceOptions = [
  'Museums',
  'Food',
  'Architecture',
  'Parks',
  'Night views',
  'Shopping',
  'Relaxed pace'
]

type FormValues = {
  city: string
  date_range: [Dayjs, Dayjs]
  transportation: string
  accommodation: string
  preferences: string[]
  free_text_input?: string
}

function createProfileId() {
  if (typeof crypto !== 'undefined' && crypto.randomUUID) {
    return `trip_${crypto.randomUUID()}`
  }
  return `trip_${Date.now()}_${Math.random().toString(36).slice(2, 12)}`
}

function getOrCreateProfileId() {
  const existing = localStorage.getItem(PROFILE_STORAGE_KEY)
  if (existing) return existing
  const profileId = createProfileId()
  localStorage.setItem(PROFILE_STORAGE_KEY, profileId)
  return profileId
}

export default function Home() {
  const [form] = Form.useForm<FormValues>()
  const navigate = useNavigate()
  const [loading, setLoading] = useState(false)
  const [progress, setProgress] = useState(0)
  const [status, setStatus] = useState('')
  const dates = Form.useWatch('date_range', form)

  const travelDays = useMemo(() => {
    if (!dates?.[0] || !dates?.[1]) return 1
    return Math.max(1, dates[1].diff(dates[0], 'day') + 1)
  }, [dates])

  useEffect(() => {
    if (!loading) return
    const interval = window.setInterval(() => {
      setProgress((current) => {
        const next = Math.min(90, current + 10)
        if (next <= 30) setStatus('Retrieving attractions...')
        else if (next <= 50) setStatus('Checking weather...')
        else if (next <= 70) setStatus('Finding hotels...')
        else setStatus('Generating itinerary...')
        return next
      })
    }, 550)
    return () => window.clearInterval(interval)
  }, [loading])

  async function handleSubmit(values: FormValues) {
    const [start, end] = values.date_range
    const days = end.diff(start, 'day') + 1
    if (days <= 0 || days > 30) {
      message.error('Travel dates must cover 1-30 days.')
      return
    }

    setLoading(true)
    setProgress(5)
    setStatus('Initializing graph workflow...')
    try {
      const profileId = getOrCreateProfileId()
      const requestData: TripFormData = {
        city: values.city,
        start_date: start.format('YYYY-MM-DD'),
        end_date: end.format('YYYY-MM-DD'),
        travel_days: days,
        transportation: values.transportation,
        accommodation: values.accommodation,
        preferences: values.preferences.map(String),
        free_text_input: values.free_text_input || '',
        profile_id: profileId,
        conversation_id: sessionStorage.getItem(CONVERSATION_STORAGE_KEY) || undefined
      }

      const response = await generateTripPlan(requestData)
      setProgress(100)
      setStatus('Complete')

      if (response.success && response.data) {
        sessionStorage.setItem('tripPlan', JSON.stringify(response.data))
        if (response.conversation_id) {
          sessionStorage.setItem(CONVERSATION_STORAGE_KEY, response.conversation_id)
        }
        if (response.memory_summary) {
          sessionStorage.setItem('tripMemorySummary', response.memory_summary)
        } else {
          sessionStorage.removeItem('tripMemorySummary')
        }
        if (response.memory_applied && response.memory_profile) {
          sessionStorage.setItem('tripMemoryApplied', 'true')
          sessionStorage.setItem('tripMemoryProfile', JSON.stringify(response.memory_profile))
        } else {
          sessionStorage.removeItem('tripMemoryApplied')
          sessionStorage.removeItem('tripMemoryProfile')
        }
        message.success('Trip plan generated.')
        window.setTimeout(() => navigate('/result'), 450)
      } else {
        message.error(response.message || 'Trip planning failed.')
      }
    } catch (error: any) {
      message.error(error.message || 'Trip planning failed.')
    } finally {
      window.setTimeout(() => {
        setLoading(false)
        setProgress(0)
        setStatus('')
      }, 700)
    }
  }

  async function handleClearMemory() {
    const profileId = localStorage.getItem(PROFILE_STORAGE_KEY)
    if (!profileId) {
      message.info('No local preference memory exists.')
      return
    }
    try {
      await clearTripMemory(profileId)
      localStorage.removeItem(PROFILE_STORAGE_KEY)
      sessionStorage.removeItem(CONVERSATION_STORAGE_KEY)
      sessionStorage.removeItem('tripMemorySummary')
      sessionStorage.removeItem('tripMemoryApplied')
      sessionStorage.removeItem('tripMemoryProfile')
      message.success('Preference memory cleared.')
    } catch (error: any) {
      message.error(error.message || 'Failed to clear preference memory.')
    }
  }

  return (
    <main className="home-page">
      <section className="hero">
        <Tag color="blue">LangChain + LangGraph</Tag>
        <h1>Plan a grounded city itinerary</h1>
        <p>
          Retrieve places, hotels, weather, and travel context, then validate the itinerary before it reaches the user.
        </p>
      </section>

      <Card className="planner-card" variant="borderless">
        <Form
          form={form}
          layout="vertical"
          initialValues={{
            city: 'New York',
            transportation: 'Public transit',
            accommodation: 'Mid-range hotel',
            preferences: ['Museums', 'Food']
          }}
          onFinish={handleSubmit}
        >
          <Row gutter={[20, 4]}>
            <Col xs={24} lg={8}>
              <Form.Item name="city" label="Destination city" rules={[{ required: true, message: 'Enter a city.' }]}>
                <Input size="large" placeholder="New York" />
              </Form.Item>
            </Col>
            <Col xs={24} lg={10}>
              <Form.Item name="date_range" label="Travel dates" rules={[{ required: true, message: 'Select dates.' }]}>
                <DatePicker.RangePicker size="large" style={{ width: '100%' }} />
              </Form.Item>
            </Col>
            <Col xs={24} lg={6}>
              <Form.Item label="Travel days">
                <div className="days-pill">{travelDays} day{travelDays === 1 ? '' : 's'}</div>
              </Form.Item>
            </Col>
          </Row>

          <Row gutter={[20, 4]}>
            <Col xs={24} md={8}>
              <Form.Item name="transportation" label="Transportation">
                <Select
                  size="large"
                  options={[
                    { value: 'Public transit', label: 'Public transit' },
                    { value: 'Walking', label: 'Walking' },
                    { value: 'Rideshare / taxi', label: 'Rideshare / taxi' },
                    { value: 'Driving', label: 'Driving' }
                  ]}
                />
              </Form.Item>
            </Col>
            <Col xs={24} md={8}>
              <Form.Item name="accommodation" label="Accommodation">
                <Select
                  size="large"
                  options={[
                    { value: 'Budget hotel', label: 'Budget hotel' },
                    { value: 'Mid-range hotel', label: 'Mid-range hotel' },
                    { value: 'Luxury hotel', label: 'Luxury hotel' },
                    { value: 'Boutique hotel', label: 'Boutique hotel' }
                  ]}
                />
              </Form.Item>
            </Col>
            <Col xs={24} md={8}>
              <Form.Item name="preferences" label="Preferences">
                <Checkbox.Group options={preferenceOptions} className="preference-grid" />
              </Form.Item>
            </Col>
          </Row>

          <Form.Item name="free_text_input" label="Additional requirements">
            <Input.TextArea
              rows={3}
              placeholder="Example: keep the pace relaxed, avoid long transfers, include one museum per day."
            />
          </Form.Item>

          {loading && (
            <div className="progress-panel">
              <Progress percent={progress} status="active" />
              <span>{status}</span>
            </div>
          )}

          <Space wrap>
            <Button type="primary" htmlType="submit" size="large" loading={loading}>
              Generate itinerary
            </Button>
            <Button icon={<DeleteOutlined />} onClick={handleClearMemory} disabled={loading}>
              Clear preference memory
            </Button>
          </Space>
        </Form>
      </Card>
    </main>
  )
}

// frontend/src/views/Home.vue
<template>
  <div class="home-container">
    <!-- 背景装饰 -->
    <div class="bg-decoration">
      <div class="circle circle-1"></div>
      <div class="circle circle-2"></div>
      <div class="circle circle-3"></div>
    </div>

    <!-- 页面标题 -->
    <div class="page-header">
      <div class="icon-wrapper">
        <span class="icon">✈️</span>
      </div>
      <h1 class="page-title">智能旅行助手</h1>
      <p class="page-subtitle">基于AI的个性化旅行规划,让每一次出行都完美无忧</p>
    </div>

    <a-card class="form-card" :bordered="false">
      <a-form
        :model="formData"
        layout="vertical"
        @finish="handleSubmit"
      >
        <!-- 第一步:目的地和日期 -->
        <div class="form-section">
          <div class="section-header">
            <span class="section-icon">📍</span>
            <span class="section-title">目的地与日期</span>
          </div>

          <a-row :gutter="24">
            <a-col :span="8">
              <a-form-item name="city" :rules="[{ required: true, message: '请输入目的地城市' }]">
                <template #label>
                  <span class="form-label">目的地城市</span>
                </template>
                <a-input
                  v-model:value="formData.city"
                  placeholder="例如: 北京"
                  size="large"
                  class="custom-input"
                >
                  <template #prefix>
                    <span style="color: #1890ff;">🏙️</span>
                  </template>
                </a-input>
              </a-form-item>
            </a-col>
            <a-col :span="6">
              <a-form-item name="start_date" :rules="[{ required: true, message: '请选择开始日期' }]">
                <template #label>
                  <span class="form-label">开始日期</span>
                </template>
                <a-date-picker
                  v-model:value="formData.start_date"
                  style="width: 100%"
                  size="large"
                  class="custom-input"
                  placeholder="选择日期"
                />
              </a-form-item>
            </a-col>
            <a-col :span="6">
              <a-form-item name="end_date" :rules="[{ required: true, message: '请选择结束日期' }]">
                <template #label>
                  <span class="form-label">结束日期</span>
                </template>
                <a-date-picker
                  v-model:value="formData.end_date"
                  style="width: 100%"
                  size="large"
                  class="custom-input"
                  placeholder="选择日期"
                />
              </a-form-item>
            </a-col>
            <a-col :span="4">
              <a-form-item>
                <template #label>
                  <span class="form-label">旅行天数</span>
                </template>
                <div class="days-display-compact">
                  <span class="days-value">{{ formData.travel_days }}</span>
                  <span class="days-unit">天</span>
                </div>
              </a-form-item>
            </a-col>
          </a-row>
        </div>

        <!-- 第二步:偏好设置 -->
        <div class="form-section">
          <div class="section-header">
            <span class="section-icon">⚙️</span>
            <span class="section-title">偏好设置</span>
          </div>

          <a-row :gutter="24">
            <a-col :span="8">
              <a-form-item name="transportation">
                <template #label>
                  <span class="form-label">交通方式</span>
                </template>
                <a-select v-model:value="formData.transportation" size="large" class="custom-select">
                  <a-select-option value="公共交通">🚇 公共交通</a-select-option>
                  <a-select-option value="自驾">🚗 自驾</a-select-option>
                  <a-select-option value="步行">🚶 步行</a-select-option>
                  <a-select-option value="混合">🔀 混合</a-select-option>
                </a-select>
              </a-form-item>
            </a-col>
            <a-col :span="8">
              <a-form-item name="accommodation">
                <template #label>
                  <span class="form-label">住宿偏好</span>
                </template>
                <a-select v-model:value="formData.accommodation" size="large" class="custom-select">
                  <a-select-option value="经济型酒店">💰 经济型酒店</a-select-option>
                  <a-select-option value="舒适型酒店">🏨 舒适型酒店</a-select-option>
                  <a-select-option value="豪华酒店">⭐ 豪华酒店</a-select-option>
                  <a-select-option value="民宿">🏡 民宿</a-select-option>
                </a-select>
              </a-form-item>
            </a-col>
            <a-col :span="8">
              <a-form-item name="preferences">
                <template #label>
                  <span class="form-label">旅行偏好</span>
                </template>
                <div class="preference-tags">
                  <a-checkbox-group v-model:value="formData.preferences" class="custom-checkbox-group">
                    <a-checkbox value="历史文化" class="preference-tag">🏛️ 历史文化</a-checkbox>
                    <a-checkbox value="自然风光" class="preference-tag">🏞️ 自然风光</a-checkbox>
                    <a-checkbox value="美食" class="preference-tag">🍜 美食</a-checkbox>
                    <a-checkbox value="购物" class="preference-tag">🛍️ 购物</a-checkbox>
                    <a-checkbox value="艺术" class="preference-tag">🎨 艺术</a-checkbox>
                    <a-checkbox value="休闲" class="preference-tag">☕ 休闲</a-checkbox>
                  </a-checkbox-group>
                </div>
              </a-form-item>
            </a-col>
          </a-row>
        </div>

        <!-- 第三步:额外要求 -->
        <div class="form-section">
          <div class="section-header">
            <span class="section-icon">💬</span>
            <span class="section-title">额外要求</span>
          </div>

          <a-form-item name="free_text_input">
            <a-textarea
              v-model:value="formData.free_text_input"
              placeholder="请输入您的额外要求,例如:想去看升旗、需要无障碍设施、对海鲜过敏等..."
              :rows="3"
              size="large"
              class="custom-textarea"
            />
          </a-form-item>
        </div>

        <!-- 提交按钮 -->
        <a-form-item>
          <a-button
            type="primary"
            html-type="submit"
            :loading="loading"
            size="large"
            block
            class="submit-button"
          >
            <template v-if="!loading">
              <span class="button-icon">🚀</span>
              <span>开始规划我的旅行</span>
            </template>
            <template v-else>
              <span>正在生成中...</span>
            </template>
          </a-button>
          <div class="memory-actions">
            <a-button type="text" size="small" :disabled="loading" @click="handleClearMemory">
              <template #icon>
                <DeleteOutlined />
              </template>
              清除偏好记忆
            </a-button>
          </div>
        </a-form-item>

        <!-- 加载进度条 -->
        <a-form-item v-if="loading">
          <div class="loading-container">
            <a-progress
              :percent="loadingProgress"
              status="active"
              :stroke-color="{
                '0%': '#667eea',
                '100%': '#764ba2',
              }"
              :stroke-width="10"
            />
            <p class="loading-status">
              {{ loadingStatus }}
            </p>
          </div>
        </a-form-item>
      </a-form>
    </a-card>
  </div>
</template>

<script setup lang="ts">
import { ref, reactive, watch } from 'vue'
import { useRouter } from 'vue-router'
import { message } from 'ant-design-vue'
import { DeleteOutlined } from '@ant-design/icons-vue'
import { clearTripMemory, generateTripPlan } from '@/services/api'
import type { TripFormData } from '@/types'
import type { Dayjs } from 'dayjs'

const PROFILE_STORAGE_KEY = 'trip_profile_id'
const CONVERSATION_STORAGE_KEY = 'trip_conversation_id'
type TripFormState = Omit<TripFormData, 'start_date' | 'end_date'> & {
  start_date: Dayjs | null
  end_date: Dayjs | null
}

const router = useRouter()
const loading = ref(false)
const loadingProgress = ref(0)
const loadingStatus = ref('')

const formData = reactive<TripFormState>({
  city: '',
  start_date: null,
  end_date: null,
  travel_days: 1,
  transportation: '公共交通',
  accommodation: '经济型酒店',
  preferences: [],
  free_text_input: ''
})

// 监听日期变化,自动计算旅行天数
watch([() => formData.start_date, () => formData.end_date], ([start, end]) => {
  if (start && end) {
    const days = end.diff(start, 'day') + 1
    if (days > 0 && days <= 30) {
      formData.travel_days = days
    } else if (days > 30) {
      message.warning('旅行天数不能超过30天')
      formData.end_date = null
    } else {
      message.warning('结束日期不能早于开始日期')
      formData.end_date = null
    }
  }
})

const createProfileId = () => {
  if (typeof crypto !== 'undefined' && crypto.randomUUID) {
    return `trip_${crypto.randomUUID()}`
  }
  return `trip_${Date.now()}_${Math.random().toString(36).slice(2, 12)}`
}

const getOrCreateProfileId = () => {
  const existing = localStorage.getItem(PROFILE_STORAGE_KEY)
  if (existing) {
    return existing
  }
  const profileId = createProfileId()
  localStorage.setItem(PROFILE_STORAGE_KEY, profileId)
  return profileId
}

const handleClearMemory = async () => {
  const profileId = localStorage.getItem(PROFILE_STORAGE_KEY)
  if (!profileId) {
    message.info('当前没有可清除的偏好记忆')
    return
  }

  try {
    await clearTripMemory(profileId)
    localStorage.removeItem(PROFILE_STORAGE_KEY)
    sessionStorage.removeItem(CONVERSATION_STORAGE_KEY)
    sessionStorage.removeItem('tripMemorySummary')
    sessionStorage.removeItem('tripMemoryApplied')
    sessionStorage.removeItem('tripMemoryProfile')
    message.success('偏好记忆已清除')
  } catch (error: any) {
    message.error(error.message || '清除偏好记忆失败')
  }
}

const handleSubmit = async () => {
  if (!formData.start_date || !formData.end_date) {
    message.error('请选择日期')
    return
  }

  loading.value = true
  loadingProgress.value = 0
  loadingStatus.value = '正在初始化...'

  // 模拟进度更新
  const progressInterval = setInterval(() => {
    if (loadingProgress.value < 90) {
      loadingProgress.value += 10

      // 更新状态文本
      if (loadingProgress.value <= 30) {
        loadingStatus.value = '🔍 正在搜索景点...'
      } else if (loadingProgress.value <= 50) {
        loadingStatus.value = '🌤️ 正在查询天气...'
      } else if (loadingProgress.value <= 70) {
        loadingStatus.value = '🏨 正在推荐酒店...'
      } else {
        loadingStatus.value = '📋 正在生成行程计划...'
      }
    }
  }, 500)

  try {
    const profileId = getOrCreateProfileId()
    const requestData: TripFormData = {
      city: formData.city,
      start_date: formData.start_date.format('YYYY-MM-DD'),
      end_date: formData.end_date.format('YYYY-MM-DD'),
      travel_days: formData.travel_days,
      transportation: formData.transportation,
      accommodation: formData.accommodation,
      preferences: formData.preferences,
      free_text_input: formData.free_text_input,
      profile_id: profileId,
      conversation_id: sessionStorage.getItem(CONVERSATION_STORAGE_KEY) || undefined
    }

    const response = await generateTripPlan(requestData)

    clearInterval(progressInterval)
    loadingProgress.value = 100
    loadingStatus.value = '✅ 完成!'

    if (response.success && response.data) {
      // 保存到sessionStorage
      sessionStorage.setItem('tripPlan', JSON.stringify(response.data))
      if (response.conversation_id) {
        sessionStorage.setItem(CONVERSATION_STORAGE_KEY, response.conversation_id)
      }
      if (response.memory_summary) {
        sessionStorage.setItem('tripMemorySummary', response.memory_summary)
      } else {
        sessionStorage.removeItem('tripMemorySummary')
      }
      if (response.memory_applied && response.memory_profile) {
        sessionStorage.setItem('tripMemoryApplied', 'true')
        sessionStorage.setItem('tripMemoryProfile', JSON.stringify(response.memory_profile))
      } else {
        sessionStorage.removeItem('tripMemoryApplied')
        sessionStorage.removeItem('tripMemoryProfile')
      }

      message.success('旅行计划生成成功!')

      // 短暂延迟后跳转
      setTimeout(() => {
        router.push('/result')
      }, 500)
    } else {
      message.error(response.message || '生成失败')
    }
  } catch (error: any) {
    clearInterval(progressInterval)
    message.error(error.message || '生成旅行计划失败,请稍后重试')
  } finally {
    setTimeout(() => {
      loading.value = false
      loadingProgress.value = 0
      loadingStatus.value = ''
    }, 1000)
  }
}
</script>

<style scoped>
.home-container {
  min-height: 100vh;
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
  padding: 60px 20px;
  position: relative;
  overflow: hidden;
}

/* 背景装饰 */
.bg-decoration {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  pointer-events: none;
  overflow: hidden;
}

.circle {
  position: absolute;
  border-radius: 50%;
  background: rgba(255, 255, 255, 0.1);
  animation: float 20s infinite ease-in-out;
}

.circle-1 {
  width: 300px;
  height: 300px;
  top: -100px;
  left: -100px;
  animation-delay: 0s;
}

.circle-2 {
  width: 200px;
  height: 200px;
  top: 50%;
  right: -50px;
  animation-delay: 5s;
}

.circle-3 {
  width: 150px;
  height: 150px;
  bottom: -50px;
  left: 30%;
  animation-delay: 10s;
}

@keyframes float {
  0%, 100% {
    transform: translateY(0) rotate(0deg);
  }
  50% {
    transform: translateY(-30px) rotate(180deg);
  }
}

/* 页面标题 */
.page-header {
  text-align: center;
  margin-bottom: 50px;
  animation: fadeInDown 0.8s ease-out;
  position: relative;
  z-index: 1;
}

.icon-wrapper {
  margin-bottom: 20px;
}

.icon {
  font-size: 80px;
  display: inline-block;
  animation: bounce 2s infinite;
}

@keyframes bounce {
  0%, 100% {
    transform: translateY(0);
  }
  50% {
    transform: translateY(-20px);
  }
}

.page-title {
  font-size: 56px;
  font-weight: 800;
  color: #ffffff;
  margin-bottom: 16px;
  text-shadow: 3px 3px 6px rgba(0, 0, 0, 0.3);
  letter-spacing: 2px;
}

.page-subtitle {
  font-size: 20px;
  color: rgba(255, 255, 255, 0.95);
  margin: 0;
  font-weight: 300;
}

/* 表单卡片 */
.form-card {
  max-width: 1400px;
  margin: 0 auto;
  border-radius: 24px;
  box-shadow: 0 30px 80px rgba(0, 0, 0, 0.4);
  animation: fadeInUp 0.8s ease-out;
  position: relative;
  z-index: 1;
  backdrop-filter: blur(10px);
  background: rgba(255, 255, 255, 0.98) !important;
}

/* 表单分区 */
.form-section {
  margin-bottom: 32px;
  padding: 24px;
  background: linear-gradient(135deg, #f5f7fa 0%, #ffffff 100%);
  border-radius: 16px;
  border: 1px solid #e8e8e8;
  transition: all 0.3s ease;
}

.form-section:hover {
  box-shadow: 0 8px 24px rgba(102, 126, 234, 0.15);
  transform: translateY(-2px);
}

.section-header {
  display: flex;
  align-items: center;
  margin-bottom: 20px;
  padding-bottom: 12px;
  border-bottom: 2px solid #667eea;
}

.section-icon {
  font-size: 24px;
  margin-right: 12px;
}

.section-title {
  font-size: 18px;
  font-weight: 600;
  color: #333;
}

/* 表单标签 */
.form-label {
  font-size: 15px;
  font-weight: 500;
  color: #555;
}

/* 自定义输入框 */
.custom-input :deep(.ant-input),
.custom-input :deep(.ant-picker) {
  border-radius: 12px;
  border: 2px solid #e8e8e8;
  transition: all 0.3s ease;
}

.custom-input :deep(.ant-input:hover),
.custom-input :deep(.ant-picker:hover) {
  border-color: #667eea;
}

.custom-input :deep(.ant-input:focus),
.custom-input :deep(.ant-picker-focused) {
  border-color: #667eea;
  box-shadow: 0 0 0 3px rgba(102, 126, 234, 0.1);
}

/* 自定义选择框 */
.custom-select :deep(.ant-select-selector) {
  border-radius: 12px !important;
  border: 2px solid #e8e8e8 !important;
  transition: all 0.3s ease;
}

.custom-select:hover :deep(.ant-select-selector) {
  border-color: #667eea !important;
}

.custom-select :deep(.ant-select-focused .ant-select-selector) {
  border-color: #667eea !important;
  box-shadow: 0 0 0 3px rgba(102, 126, 234, 0.1) !important;
}

/* 天数显示 - 紧凑版 */
.days-display-compact {
  display: flex;
  align-items: center;
  justify-content: center;
  height: 40px;
  padding: 8px 16px;
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
  border-radius: 12px;
  color: white;
}

.days-display-compact .days-value {
  font-size: 24px;
  font-weight: 700;
  margin-right: 4px;
}

.days-display-compact .days-unit {
  font-size: 14px;
}

/* 偏好标签 */
.preference-tags {
  display: flex;
  flex-wrap: wrap;
  gap: 8px;
}

.custom-checkbox-group {
  display: flex;
  flex-wrap: wrap;
  gap: 8px;
  width: 100%;
}

.preference-tag :deep(.ant-checkbox-wrapper) {
  margin: 0 !important;
  padding: 8px 16px;
  border: 2px solid #e8e8e8;
  border-radius: 20px;
  transition: all 0.3s ease;
  background: white;
  font-size: 14px;
}

.preference-tag :deep(.ant-checkbox-wrapper:hover) {
  border-color: #667eea;
  background: #f5f7ff;
}

.preference-tag :deep(.ant-checkbox-wrapper-checked) {
  border-color: #667eea;
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
  color: white;
}

/* 自定义文本域 */
.custom-textarea :deep(.ant-input) {
  border-radius: 12px;
  border: 2px solid #e8e8e8;
  transition: all 0.3s ease;
}

.custom-textarea :deep(.ant-input:hover) {
  border-color: #667eea;
}

.custom-textarea :deep(.ant-input:focus) {
  border-color: #667eea;
  box-shadow: 0 0 0 3px rgba(102, 126, 234, 0.1);
}

/* 提交按钮 */
.submit-button {
  height: 56px;
  border-radius: 28px;
  font-size: 18px;
  font-weight: 600;
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
  border: none;
  box-shadow: 0 8px 24px rgba(102, 126, 234, 0.4);
  transition: all 0.3s ease;
}

.submit-button:hover {
  transform: translateY(-2px);
  box-shadow: 0 12px 32px rgba(102, 126, 234, 0.5);
}

.submit-button:active {
  transform: translateY(0);
}

.button-icon {
  margin-right: 8px;
  font-size: 20px;
}

.memory-actions {
  margin-top: 10px;
  text-align: center;
}

.memory-actions :deep(.ant-btn) {
  color: #6b7280;
}

/* 加载容器 */
.loading-container {
  text-align: center;
  padding: 24px;
  background: linear-gradient(135deg, #f5f7fa 0%, #ffffff 100%);
  border-radius: 16px;
  border: 2px dashed #667eea;
}

.loading-status {
  margin-top: 16px;
  color: #667eea;
  font-size: 18px;
  font-weight: 500;
}

/* 动画 */
@keyframes fadeInDown {
  from {
    opacity: 0;
    transform: translateY(-30px);
  }
  to {
    opacity: 1;
    transform: translateY(0);
  }
}

@keyframes fadeInUp {
  from {
    opacity: 0;
    transform: translateY(30px);
  }
  to {
    opacity: 1;
    transform: translateY(0);
  }
}
</style>
